# Generated by Django 3.0.4 on 2021-01-28 12:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blocks', '0002_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='My',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
    ]
