# Generated by Django 3.0.4 on 2021-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0003_my'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
