# Generated by Django 3.0.4 on 2021-01-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blocks', '0004_auto_20210128_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('height', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('hash', models.CharField(max_length=64, unique=True)),
                ('date', models.DateTimeField()),
                ('miner', models.CharField(max_length=64)),
                ('transaction_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='My',
        ),
    ]
